In [3]:
 # IMPORT LIBRARIES
import pandas as pd
import numpy as np
import os.path
import datetime
import scipy as sp
import pytz 

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib
import itertools
import importlib as imp
from cvxpy import *
from sklearn.metrics import mean_squared_error
from math import sqrt

#import Modules.SolarDisaggregation as sd #disaggregateSolar, createTempInput,disaggregateSolarIndividualSparse,
#import Modules.PecanTempMod as ptm
#import Modules.EpiDataSolarMod as epd
from copy import * 
%matplotlib inline

In [4]:
from bokeh.io import push_notebook, show, output_notebook
from bokeh.layouts import row
from bokeh.plotting import figure
output_notebook()

In [32]:
import sqlalchemy as sq
engine = sq.create_engine("postgresql+psycopg2://7gi6wEsghEgO:mnMRXtOPVvkX@dataport.pecanstreet.org:5434/postgres")

In [6]:
the_frame = pd.read_sql_query('SELECT table_schema,table_name FROM information_schema.tables ORDER BY table_schema,table_name;', engine)
the_frame

           table_schema                           table_name
0                caliso                      demand_forecast
1                caliso                         interval_lmp
2                caliso                        sys_load_rsrc
3                caliso                          ws_forecast
4       electricity_sec                       egauge_1s_2014
5       electricity_sec                       egauge_1s_2015
6       electricity_sec                       egauge_1s_2016
7       electricity_sec                       egauge_1s_2017
8                 ercot            actual_load_xweather_zone
9                 ercot             ancillary_service_offers
10                ercot                              dam_spp
11                ercot                      hdl_ldl_summary
12                ercot            hourly_realtime_vs_actual
13                ercot      hourly_resource_outage_capacity
14                ercot  hourly_ruc_transmission_constraints
15                ercot                    knowledge_reports
16                ercot    load_forecast_xforecast_zone_7day
17                ercot     load_forecast_xweather_zone_7day
18                ercot                    peaker_net_margin
19                ercot                         realtime_lmp
20                ercot                         realtime_spp
21                ercot                    solar_actual_5min
22                ercot     solar_hourly_actual_and_forecast
23                ercot               solar_pwr_pot_forecast
24                ercot                                swcap
25                ercot                   system_wide_demand
26                ercot                     wind_actual_5min
27                ercot      wind_hourly_actual_and_forecast
28                ercot                   wind_output_hourly
29   information_schema    administrable_role_authorizations
..                  ...                                  ...
188                 pjm                 ancillary_svc_lmp_hr
189                 pjm                     day_ahead_lmp_hr
190                 pjm                     real_time_lmp_hr
191                 pjm        verified_ancillary_svc_lmp_hr
192                 pjm                      verified_lmp_hr
193              public                   pg_stat_statements
194          university                          audits_2011
195          university               audits_2013_appliances
196          university        audits_2013_duct_leakage_eval
197          university                     audits_2013_main
198          university                 civita_text_messages
199          university            egauge_detailed_registers
200          university             electricity_egauge_15min
201          university             electricity_egauge_hours
202          university           electricity_egauge_minutes
203          university                    electric_vehicles
204          university                              gas_ert
205          university            indoor_temperature_sensor
206          university                       pricing_events
207          university         pricing_events_notifications
208          university         survey_2011_all_participants
209          university         survey_2012_all_participants
210          university       survey_2012_field_descriptions
211          university         survey_2013_all_participants
212          university       survey_2013_field_descriptions
213          university         survey_2014_all_participants
214          university       survey_2014_field_descriptions
215          university                       water_capstone
216          university                            water_ert
217          university                              weather

[218 rows x 2 columns]

In [96]:
 # import psycopg2
query="""SELECT dataid, localhour, use, gen, air1, air2, air3, airwindowunit1, furnace1, furnace2 FROM university.electricity_egauge_hours
WHERE localhour
BETWEEN '01-01-2016' AND '01-1-2017' AND dataid in (22,    59,  77,     86,
267,    275,    280,    297,    330,    347,    364,    370,
         1415,   1450,   1463,   1464,   1479,   1500,   1507,   1508,
         1524,   1551,   1577,   1586,   1589,   1597,   1601,   1617,
         1629,   1632,   1642,   1681,   1696,   1697,   1700,   1714,
         1718,   1731,   1766,   1782,   1790,   1791,   1792,   1796,
         1800,   1801,   1830,   1832,   1845,   1854,   1879,   1889,
         1947,   1953,   1994,   2004,   2018,   2031,   2034,   2062,
         2072,   2075,   2094,   2129,   2144,   2156,   2158,   2171,
         2199,   2204,   2207,   2233,   2242,   2247,   2335,   2337) """


# query="""SELECT *
# FROM university.electricity_egauge_hours
# LIMIT 10 """

egauge = pd.read_sql_query(query,engine)
egauge.shape

(379346, 10)

In [97]:
np.unique(egauge['dataid'])

array([  59,   77,   86,  370, 1415, 1450, 1463, 1500, 1507, 1524, 1551,
       1589, 1617, 1629, 1632, 1642, 1681, 1696, 1697, 1700, 1714, 1718,
       1731, 1766, 1790, 1791, 1792, 1796, 1800, 1801, 1830, 1879, 1947,
       1953, 2004, 2018, 2034, 2072, 2094, 2129, 2156, 2158, 2171, 2199,
       2204, 2233, 2242, 2335, 2337])

In [90]:
 # import psycopg2
query="""SELECT distinct(dataid) FROM university.electricity_egauge_hours
"""


# query="""SELECT *
# FROM university.electricity_egauge_hours
# LIMIT 10 """

dataids = pd.read_sql_query(query,engine)

AttributeError: 'Series' object has no attribute 'sort'

In [91]:
np.sort(dataids['dataid'])

array([    22,     26,     48,     54,     59,     68,     77,     86,
           93,     94,    101,    114,    115,    121,    130,    135,
          160,    171,    187,    203,    222,    232,    243,    252,
          267,    275,    280,    297,    330,    347,    364,    370,
          379,    410,    434,    436,    457,    470,    483,    484,
          490,    491,    499,    503,    507,    508,    516,    527,
          545,    547,    555,    573,    575,    580,    585,    604,
          621,    624,    645,    661,    668,    698,    739,    744,
          765,    772,    774,    781,    796,    821,    861,    871,
          878,    890,    898,    900,    930,    936,    946,    954,
          974,    980,    991,    994,   1037,   1069,   1086,   1103,
         1105,   1153,   1167,   1169,   1185,   1192,   1202,   1283,
         1310,   1314,   1331,   1334,   1350,   1354,   1392,   1403,
         1415,   1450,   1463,   1464,   1479,   1500,   1507,   1508,
         1524,   1551,   1577,   1586,   1589,   1597,   1601,   1617,
         1629,   1632,   1642,   1681,   1696,   1697,   1700,   1714,
         1718,   1731,   1766,   1782,   1790,   1791,   1792,   1796,
         1800,   1801,   1830,   1832,   1845,   1854,   1879,   1889,
         1947,   1953,   1994,   2004,   2018,   2031,   2034,   2062,
         2072,   2075,   2094,   2129,   2144,   2156,   2158,   2171,
         2199,   2204,   2207,   2233,   2242,   2247,   2335,   2337,
         2354,   2360,   2361,   2365,   2366,   2378,   2401,   2449,
         2458,   2461,   2465,   2470,   2472,   2505,   2510,   2520,
         2523,   2532,   2557,   2575,   2606,   2638,   2641,   2667,
         2710,   2742,   2750,   2751,   2755,   2769,   2787,   2814,
         2815,   2818,   2824,   2829,   2845,   2859,   2864,   2873,
         2903,   2907,   2925,   2931,   2945,   2953,   2965,   2974,
         2980,   2986,   2992,   2995,   3009,   3032,   3036,   3039,
         3044,   3087,   3092,   3104,   3126,   3134,   3143,   3160,
         3192,   3204,   3215,   3221,   3224,   3235,   3263,   3268,
         3273,   3299,   3310,   3353,   3367,   3368,   3392,   3394,
         3401,   3411,   3413,   3425,   3426,   3443,   3456,   3482,
         3484,   3500,   3504,   3506,   3510,   3519,   3527,   3531,
         3538,   3544,   3577,   3615,   3631,   3632,   3635,   3649,
         3652,   3676,   3678,   3687,   3719,   3721,   3723,   3734,
         3736,   3778,   3789,   3795,   3806,   3829,   3831,   3849,
         3864,   3873,   3883,   3886,   3893,   3916,   3918,   3935,
         3938,   3953,   3964,   3967,   3973,   4000,   4022,   4031,
         4042,   4053,   4083,   4095,   4135,   4147,   4154,   4193,
         4213,   4220,   4224,   4251,   4296,   4297,   4298,   4302,
         4313,   4321,   4329,   4336,   4342,   4352,   4357,   4373,
         4375,   4383,   4416,   4438,   4447,   4473,   4495,   4499,
         4505,   4514,   4526,   4544,   4575,   4590,   4601,   4633,
         4641,   4660,   4670,   4674,   4699,   4703,   4732,   4761,
         4767,   4773,   4776,   4800,   4830,   4856,   4864,   4874,
         4910,   4920,   4922,   4927,   4934,   4944,   4946,   4956,
         4957,   4967,   4974,   4998,   5009,   5026,   5035,   5060,
         5087,   5109,   5129,   5164,   5187,   5209,   5218,   5226,
         5246,   5252,   5262,   5271,   5275,   5279,   5288,   5298,
         5317,   5356,   5357,   5371,   5395,   5400,   5403,   5438,
         5439,   5448,   5449,   5450,   5456,   5485,   5539,   5545,
         5552,   5568,   5615,   5652,   5658,   5673,   5677,   5718,
         5728,   5738,   5746,   5749,   5759,   5778,   5784,   5785,
         5786,   5796,   5809,   5810,   5814,   5817,   5852,   5874,
         5889,   5892,   5904,   5909,   5921,   5938,   5944,   5949,
         5959,   5972,   5994,   6012,   6061,   6063,   6072,   6078,
         6083,   6101,   6108,   6121,   6125,   6139,   6148,   6165,
         6174,   6191,   6248,   6264,   6266,   6268,   6286,   6324,
         6334,   6348,   6377,   6378,   6412,   6418,   6423,   6429,
         6460,   6497,   6498,   6500,   6536,   6545,   6547,   6578,
         6593,   6614,   6636,   6643,   6673,   6688,   6689,   6691,
         6692,   6730,   6799,   6800,   6826,   6836,   6871,   6887,
         6888,   6910,   6911,   6941,   6956,   6960,   6979,   6990,
         7001,   7013,   7016,   7017,   7024,   7030,   7036,   7057,
         7062,   7108,   7114,   7117,   7122,   7166,   7208,   7240,
         7276,   7287,   7319,   7361,   7390,   7408,   7409,   7429,
         7436,   7468,   7491,   7504,   7510,   7512,   7527,   7531,
         7536,   7541,   7549,   7560,   7585,   7587,   7597,   7617,
         7627,   7638,   7639,   7641,   7680,   7693,   7703,   7719,
         7731,   7739,   7741,   7764,   7767,   7769,   7787,   7788,
         7792,   7793,   7794,   7800,   7818,   7850,   7863,   7866,
         7875,   7881,   7893,   7900,   7901,   7940,   7951,   7965,
         7973,   7982,   7984,   7989,   8029,   8031,   8034,   8046,
         8047,   8059,   8061,   8071,   8079,   8084,   8086,   8092,
         8117,   8121,   8122,   8142,   8155,   8156,   8163,   8183,
         8188,   8197,   8198,   8201,   8218,   8236,   8243,   8273,
         8282,   8292,   8317,   8328,   8342,   8368,   8386,   8395,
         8419,   8467,   8555,   8565,   8574,   8589,   8597,   8600,
         8622,   8626,   8645,   8669,   8729,   8730,   8733,   8736,
         8741,   8767,   8807,   8829,   8847,   8848,   8852,   8857,
         8862,   8872,   8886,   8890,   8942,   8956,   8961,   8967,
         8986,   8995,   9001,   9019,   9036,   9052,   9085,   9121,
         9134,   9139,   9141,   9142,   9156,   9160,   9165,   9182,
         9195,   9201,   9206,   9213,   9215,   9233,   9235,   9237,
         9248,   9251,   9277,   9278,   9295,   9333,   9340,   9341,
         9343,   9356,   9370,   9434,   9451,   9462,   9484,   9488,
         9498,   9499,   9509,   9548,   9555,   9578,   9585,   9605,
         9609,   9610,   9612,   9613,   9624,   9631,   9642,   9643,
         9647,   9654,   9670,   9674,   9688,   9701,   9729,   9737,
         9745,   9766,   9771,   9773,   9775,   9776,   9803,   9818,
         9830,   9836,   9846,   9875,   9912,   9915,   9919,   9921,
         9922,   9923,   9926,   9929,   9931,   9932,   9933,   9934,
         9935,   9936,   9937,   9938,   9939,   9942,   9958,   9971,
         9981,   9982,   9983, 100055, 100056, 100059, 100062, 100063,
       100064, 100065, 100066, 100069, 100082, 100084, 100085, 100087,
       100088, 100089, 100091, 100092, 100094, 100097, 100099, 100101,
       100102, 100103, 100106, 100107, 100108, 100109, 100111, 100113,
       100115, 100116, 100118, 100121, 100135, 100142, 100153, 100160,
       100167, 100168, 100175, 100177, 100178, 100179, 100183, 100186,
       100188, 100189, 100207, 100211, 100212, 100213, 100214, 100215,
       100216, 100218, 100219, 100220, 100221, 100224, 100225, 100226,
       100230, 100232, 100235, 100236, 100237, 100238, 100240, 100241,
       100243, 100244, 100245, 100248, 100251, 100252, 100253, 100254,
       100255, 100256, 100257, 100267])

In [72]:
query = """SELECT * FROM university.weather WHERE latitude = 40.027278 AND localhour 
BETWEEN '01-01-2016' AND '01-1-2017' """
#query = 'SELECT * FROM university.weather LIMIT 100'
weather = pd.read_sql_query(query,engine)
weather.head()

,localhour,latitude,longitude,tz_offset,summary,ozone,ozone_error,temperature,temperature_error,dew_point,...,pressure_error,wind_speed,wind_speed_error,cloud_cover,cloud_cover_error,wind_bearing,precip_intensity,precip_intensity_error,precip_probability,precip_type
0,2016-01-01 00:00:00-06:00,40.027278,-105.256111,-7,Partly Cloudy,299.98,None,7.83,None,2.09,...,None,3.72,None,0.36,None,267,0.0,None,0.0,None
1,2016-01-01 01:00:00-06:00,40.027278,-105.256111,-7,Clear,302.36,None,9.41,None,3.42,...,None,3.49,None,0.01,None,273,0.0,None,0.0,None
2,2016-01-01 02:00:00-06:00,40.027278,-105.256111,-7,Clear,304.74,None,9.15,None,2.84,...,None,3.78,None,0.00,None,272,0.0,None,0.0,None
3,2016-01-01 03:00:00-06:00,40.027278,-105.256111,-7,Clear,307.12,None,8.23,None,1.25,...,None,3.36,None,0.00,None,263,0.0,None,0.0,None
4,2016-01-01 04:00:00-06:00,40.027278,-105.256111,-7,Clear,313.39,None,7.30,None,0.63,...,None,3.69,None,0.00,None,272,0.0,None,0.0,None

In [155]:
egauge['cooling'] = np.sum( egauge[['air1','air2','air3','airwindowunit1']] , 1 )
egauge['heating'] = np.sum( egauge[['furnace1', 'furnace2']] , 1 )

egauge1 = egauge[['dataid','localhour','use','cooling','heating']]

In [156]:
egauge2 = egauge1.merge(weather, on='localhour')

In [172]:
did = np.unique(egauge2['dataid'])
i=0

In [ ]:
###### d = did[i]
i+=1
tmp = egauge2.loc[egauge2['dataid']==d,]
plt.plot(tmp['temperature'], tmp['use'], '.')
plt.title(d)
plt.show()

In [198]:
ind = [d in [1415, 1463, 1589] for d in egauge2['dataid']]
testhome1 = egauge2.loc[egauge2['dataid']==86,:]
testhome2 = egauge2.loc[egauge2['dataid']==370,:]
testhome3 = egauge2.loc[egauge2['dataid']==1697,:]

In [199]:
testhome1.to_csv('/Users/michaelangelo/repos/HVACDisagg/testhome1.csv', index = False)
testhome2.to_csv('/Users/michaelangelo/repos/HVACDisagg/testhome2.csv', index = False)
testhome3.to_csv('/Users/michaelangelo/repos/HVACDisagg/testhome3.csv', index = False)

In [171]:
testhome1.reset_index().loc[4000:4010,:]

,index,dataid,localhour,use,cooling,heating,latitude,longitude,tz_offset,summary,...,pressure_error,wind_speed,wind_speed_error,cloud_cover,cloud_cover_error,wind_bearing,precip_intensity,precip_intensity_error,precip_probability,precip_type
4000,177760,1415,2016-06-15 17:00:00-05:00,3.199250,1.602400,0.350183,40.027278,-105.256111,-6,Clear,...,None,5.43,None,0.14,None,102,0.0019,None,0.05,rain
4001,177804,1415,2016-06-15 18:00:00-05:00,3.845817,1.628267,0.372600,40.027278,-105.256111,-6,Clear,...,None,6.70,None,0.17,None,104,0.0040,None,0.14,rain
4002,177848,1415,2016-06-15 19:00:00-05:00,1.550150,0.954500,0.236567,40.027278,-105.256111,-6,Clear,...,None,5.71,None,0.21,None,102,0.0031,None,0.10,rain
4003,177892,1415,2016-06-15 20:00:00-05:00,2.843167,2.001800,0.485783,40.027278,-105.256111,-6,Clear,...,None,3.14,None,0.17,None,76,0.0011,None,0.02,rain
4004,177936,1415,2016-06-15 21:00:00-05:00,2.741950,0.979283,0.259467,40.027278,-105.256111,-6,Clear,...,None,2.30,None,0.13,None,343,0.0000,None,0.00,None
4005,177980,1415,2016-06-15 22:00:00-05:00,3.074533,1.566017,0.419917,40.027278,-105.256111,-6,Clear,...,None,4.23,None,0.01,None,285,0.0000,None,0.00,None
4006,178024,1415,2016-06-15 23:00:00-05:00,1.203783,0.733350,0.212067,40.027278,-105.256111,-6,Clear,...,None,4.34,None,0.00,None,271,0.0000,None,0.00,None
4007,178068,1415,2016-06-16 00:00:00-05:00,1.201433,0.734250,0.228133,40.027278,-105.256111,-6,Clear,...,None,5.07,None,0.00,None,255,0.0000,None,0.00,None
4008,178112,1415,2016-06-16 01:00:00-05:00,0.806000,0.449667,0.141433,40.027278,-105.256111,-6,Clear,...,None,5.07,None,0.05,None,274,0.0000,None,0.00,None
4009,178156,1415,2016-06-16 02:00:00-05:00,1.007517,0.621400,0.190417,40.027278,-105.256111,-6,Clear,...,None,3.61,None,0.05,None,277,0.0000,None,0.00,None
4010,178200,1415,2016-06-16 03:00:00-05:00,0.769533,0.410333,0.120617,40.027278,-105.256111,-6,Clear,...,None,3.07,None,0.04,None,276,0.0000,None,0.00,None